### ISSUE TITLE
滚动模式下会经常跳到下一章节的同一位置

### ISSUE THREAD

**Issue by yuweiping** [yingbing-developer/uni-readPage#1]
通过currentChange 方法记录页面变化。发现有问题，正常情况下到第53章的时候，start应该从0开始，实际变化很大。导致页面不连贯了。
11:28:15.940 更新阅读记录:start 2554   第五十二章 怎么办？ at pages/content/index.vue:342
11:28:28.787 更新阅读记录:start 2851   第五十二章 怎么办？ at pages/content/index.vue:342
11:28:34.126 更新阅读记录:start 3106   第五十二章 怎么办？ at pages/content/index.vue:342
11:28:39.942 更新阅读记录:start 2515   第五十三章 大壮啊——！（国庆节快乐！） at pages/content/index.vue:342

**Comment by yingbing-developer** [comment]
好的，收到了，感谢回复，我尽快修复这些问题

**Comment by yuweiping** [comment]
文字有重叠找到原因了。computedText方法中 lineWidth += context.measureText(content[i]).width; 写的位置太靠前，如果有\n\r就会导致计算不准确。

for ( let i = lastIndex; i < content.length; i++ ) {
							if ( JSON.stringify(content[i]) == JSON.stringify('\r') || JSON.stringify(content[i]) == JSON.stringify('\n') ) {
								lastIndex = i + 1;
								break;
							} else if ( lineWidth >= this.viewWidth - (2 * this.pageProp.slide) ) {
								lastIndex = i;
								break;
							} else {
								strs[strs.length - 1] += content[i];
								lastIndex = i;
							}
							lineWidth += context.measureText(content[i]).width;
						}

**Comment by yingbing-developer** [comment]
重构已经完成了，可以开始试用了，期待你的反馈

**Comment by yingbing-developer** [comment]
空格得问题已经修复了，更新在了git上，滚动位置得问题，我还没试出来，感谢反馈

**Comment by yingbing-developer** [comment]
又更新了一个版本，你再测试下滚动有问题没有

**Comment by yuweiping** [comment]
更新后貌似没问题了，等我再测测。
还有俩小问题，1. 启动的时候有如下报错，好像不影响使用。2.滚动模式下好像@currentChange 不触发了。

13:04:49.514 cid unmatched [object Object] at view.umd.min.js:1
13:04:49.536 TypeError: Invalid attempt to destructure non-iterable instance.
13:04:49.556 In order to be iterable, non-array objects must have a [Symbol.iterator]() method. at view.umd.min.js:1
13:04:50.606 初始化reader组件 241 at pages/content/index.vue:234
13:04:51.719 init at uni_modules/yingbing-ReadPage/components/scroll-page/scroll-page.vue:307 at app-view.js:8928

**Comment by yingbing-developer** [comment]
你再试下吧，可能和延迟有关，还有请问下你觉得滚动模式有什么需要改进得地方吗

**Comment by yuweiping** [comment]
有时候加载新章节不太流畅，比方说分了15页，有的时候加载后跳到当前章节的13页有时候14页，还见过一次跳到第9页的。
关了预加载也会这样。

**Comment by yingbing-developer** [comment]
我提交了一个新版本，你再试试

**Comment by yingbing-developer** [comment]
我修改了一下，你再试试

**Comment by yuweiping** [comment]
我在 bindScrollEvent方法中打印了scrollTop。
重置pullup 之后不输出或者输出一次scrollTop的没问题，打印两次的跳的就有问题。

20:24:51.867 重置pullup at uni_modules/yingbing-ReadPage/components/scroll-page/scroll-page.vue:246 at app-view.js:8985
20:24:52.007 [Number] 34400  at uni_modules/yingbing-ReadPage/components/scroll-page/scroll-page.vue:330 at app-view.js:8985
20:24:52.049 [Number] 23087  at uni_modules/yingbing-ReadPage/components/scroll-page/scroll-page.vue:330 at app-view.js:8985

**Comment by yingbing-developer** [comment]
我再研究研究这个，得花些时间
